language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  user: "Pavo-IM"
  password:
    secure: sOfjNsqNj4VaNvC1LMKL5w6qDrPGPJOvW49nGefTIm6pjIRGo8uscHU7JWrCuqvYIS4Tx2QpGJlzDOoCW/XB4nhaRLkLr8BOawO9n0Ao3z3CytKtFdRdOiGFm88Rvfn3hSwNyIqJw77tYh2DN5qBhS+847j+dgG9SNHKE5Yi003ARa2of2rCkSzEfa7+CPNsPX2E4dGZiFt+lKCaEOKSomt7/HkNeTwtj8bN1Doi99CTXtCmHSlE53hAXuC+PD3VsyPTwOF3EB41EGZdYmj1334ZdwoHP+7/AiYQEv11NpuwdZqvoeoXpFt23TfvEprwwBDGKxooppf54uYFVADxq3pfkcyNmUKFxtLLZGuHHwDXq4TYiVFW55crpJ2CpJkemomWmgZBrefYm+R0F7vjVKZbUW482WnJ++pXSc969CifL/H1cZ4Uoc79Rx2YtMHLvDJ6J4LTh9fj6LKm6Pk67pFmtVXY4tZ7dz7n5S9Um0e2wbrm5Q1VxhHAP5/6Y/JtqVEUcGPYg5i3C3rJAIgI7Oyik/HmQZS5Pj/0cuNrEFavIJ9VyGjfJ41w8n9Tg4cEIjiO0j/1G8302noULumx3EMvpqCoOW/iz/gFcbcewuht07/Hu8O83sh7+o8BMufev96KxxCwxcBAAkzyYbxLSG+UIKdiz5+nUiTmzY384Vc=
  file: "$COMMIT.zip"
  skip_cleanup: true
  on:
    tags: true
    repo: Pavo-IM/AGPMInjector
