language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  file: "$COMMIT.zip"
  api-key:
    secure: VQWvPSDqkonwYr5UqW62Uu89MfypBi8tBK1anUKB8eiHgcMFI92q5AMl9U+BfTU1MCNvIhijPhxQGGH/esJJrNnqSVNq3/POLv80OnYHkjixdUpCG2A0AFj0QGZmiIlx0FLkq7l3UlSYMAkf2SbHuWNzj7RkpZqVxHWcE+YKxdx0tMUa+NtPRharbuxBaPu6tVOTsBBTfuR9Tx13NEZMUB1W8G/GLL1/ZxXlhl60AoDzJIEd1ypoL/HeNDgFVH3fy6BGBqvP6QElpZYRo+PMdUKi+L1z6XDdpQ1Vu4HJ1IU3GtDK8INZaIiJK9DdEjtoC6rEpoHgpsc78+qf3/88Wr6tQ5aZh+zEgtmYQ18RPgsgfJ72aLppGOiGDsK7OMyi483ZkDvWHl5AuKXR+xJEFTZdkNNVTcEuaM4o09RwY/O2eZW/mm9XJoFfuZDsQ1mecg01474Nnx1JjcdOY/IkkUMamnEde8Kic9JwTEMa0QxFO2KbwE9tpXHzCyjW8yqx1fzp8EgKGi2XVNbFnIYAdeb4lScQewqT04iOPAOrSaFvtu9CdSCm8cKB+gTRCdvqqqSTM6AKxl1BNEwWDUoNGr+iMrTxuJ1+m0ZpH4cspsXDiUCpnAX1+Aoy0u68Lo5eqP+xk/OuMemeTdpNXcp4Qx/vbxpvWe/z6HCkM6Yg95I=
  skip_cleanup: true
  on:
    repo: Pavo-IM/AGPMInjector
