language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  api_key:
    secure: N0JuaIne+WGIk7QR1aYgt2ZUEY7AatY4y58Vf9i7lC3iNKUzhswGBZe4OKg4wCKOHDDefn6Dud14nOIZbrsGenGjcUdQNjEFVDkxClq6LcWiAk68/SC+HgmnUkKNYTi6ErUKaetwhFPKK9/aJPlA3BurNAbgb3ZahFX1IIzde4ETfptlrr/sAmbPOZWW0eAm8lXpwxXr6CWeXYYhF2EOtlInzJA9hma0e7noEalcI4LZEAlfnW4FQPjoljXpm4+NHqRHneq1Txdh/54o21mJMpE0CzW25KGaGlRCnmouegUu4yGkvGnrHWYpWhtPvVvAswWrhe8XEmrfYwOIVaQ+idM1/MLqr+khkHBUjVp7h2uueqMBqWvOwIMnKN1aGw7xdlBxtwJaaSBFivfqocB3XSGK69rtaM2mUxKVuU+H9pf+YNuZ35Pyrymu6MO5HrwNVXr8ulSnfAqR8l3z5hOb0AKuItBBA25BvhhY6WIR260m2Me/hnVVuNbiKbFT6dyqKDltW6q89Rxv3MGra/kkluQ9QYG2ipy8z/Gmwr8OVS5B5lrj95a2RrOVtB1VOloQ8oNAlJZpN40NclLGR9yfbnhEH4IwrLqLF2UcU8+nUjNdbFbV99TDc6c48wCo1tEBIi1rym9WtlE+cg+JqhDmjd8grTgjkWcT31UIP+N/hxo=
  file: "$COMMIT.zip"
  on:
    repo: Pavo-IM/AGPMInjector
