language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  api_key:
    secure: BttC9PtiJqHA2/uw/T+XiF4kMpzmaofQu1G/m3mtMG+nQ3Mp3a3jXYnJf73cGD4dOxlatndCrIR+QLd0WcVmy3J6Zmp6keyT3YLJmjIimhdbvmYAxIs9ftp8c6B1YAoSwjuOSJUQq5R5IIgzTmrUAJgfw4orhQEik46UIVOfgqUaEfRAX6xTKv/Oh0Jv2EaD16lgGSXUOweqfZAs1BWJSdI9SaVICQA49HQIm5unj3MCP57yAOnxeuRCs/9YG0ofpFYFprnf/AuyUF4M7LoCE09VYkN9+qDG0wOCZK35arUWji8r/ZnB1AG0fCKybLFWxoULE/Agn4CSISzhnND6mxVWbuubeB75iDIqsfPLXYXXLhwK5i1R4c7nU0BGS3jU4t6Ud9yh3Y+CTNKRLQ+u1AT1dcipI9y63vpcMiUdEZdpzD6ksTtxpPybcjueIcUknSJZBwVgTjnxw3fwvEKxMJt5rOPqbX81PC/a2oKnnoeOl8N7JOGfTBxYR3p+U1cBjDIBJ/VjN8owVwJ0cw82T0viJcZHSMdrDuTMWXUXNFHNvwKz/w+GU0oZlY/dgaYsbFPg95LHzmSudGq5xzJFrwIsGotFhzDGysNLd9gTeTfd8yjEkdxvZmdGHmm9x8xbDZBNM4HVHzerRKxZwVK7oX4y8MUq0RwysJlZD5fm4Nc=
  file: "$COMMIT.zip"
  on:
    repo: Pavo-IM/AGPMInjector
