language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  file: "$COMMIT.zip"
  skip_cleanup: true
  on:
    repo: Pavo-IM/AGPMInjector
  api-key:
    secure: rOHVWNMC3dB/RXcpNYfzI8amzMhBXY1guFbBV6z+MVGocBfC6Sr3tvoFtGoNZUlu+jrzt0uvCCvxAH8fR4cZ0A3b0nDhBXbop/rNC0x2D9wv/mmHZ2jtqg/wN9vlSzPVlxz5B31Py/xCUN11eSLTklvzsz/vqqjpgPyBKLp004S1LPHdJN3GS53VWeEPKlBElJ2tTbWGcCxaU93vj9wdZK4dBEfOALn36T3hCyLAEd4X9xLa0grGuzhBTPKNb2gIeQARJzMhGa0H0QxaTU2dB/FXsXB85sKDF8a860GnZC3pN3vn5vNS850/q/TJqhO3jDMVcHEC6Mfl2NaU7/pVnWqHuvpP1gE52NVP+D0SHSxmwGAp7mAHezyY9M/XQEyHLLBaHCUYR75C9zMrImDl3y28giAtbgVzMGRw64YoKUxsgsRkgTwovVhrpo9Fza1N9jX7w9eQIXPiqndLLIvRdDaR/J0ub1UjFIHFDILMooqA2h37P9N+f1R2LJgVaFi6n1KZmOXkUDwRZbRwOxA4c1NrzFvwK/9ihd29e4DN05JHN5/hZg4KmQNGq9KlL75FuV1PMdAaAjH+1kwEuwWheBC1aCGEwNvf5CcWMYjEnGaiJ7Itv5f0n5bVhNOf0ZcxLSDiofd9IqrQvm0SGZlBdXndeXb6RdYEBEDTKwWpy5U=
