language: swift
osx_image: xcode10.1
xcode_workspace: AGPMInjector.xcworkspace
xcode_scheme: AGPMInjector
platform: macOS
os: osx
before_script:
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisDevProfile.enc -d -a -out scripts/profile/TravisDevProfile
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
env:
  global:
      - secure: Jee0+BAq5auXWb3LXhk+BatJ7ZKyFhcu3iK+UqfL3gHfIfr1j2CpeEjOyNTqTodP0jZ99iVQMJ3kRy6/cNK+3ew1fiPFsuOFUQCQhoIc8lHdj58rUPgazUI/h/l3Iwl/6ZQzNyL6MueLoGS31vOFheMC3Bjot12icdsPfrtsSglrHIgFR7W5ujORvsZ/1ygpa3l/NlZxpT7ibGMR98jDjVgHDdHdOgW4GvXaJz9b1O/5Hb3aBJvceXD1P65UmjNLPfm8VQouSvvGB1L1soVoEY6x0Vlk1l7XEVACZl6kPloZ0LqoYqHmyk21k85LQW19FOF8yerIwCRPBze51qHe1fAc+bwHF6JrMVRMjsv7vNEcBUx8z7i6xe3GeufcMpSib11jpah3Gt60UNNsEFRakE7DLNIDWk9nDCAvG5xKBwciStMMK7KB3Wsdp5W3EtR67VWP10+UBpry1CD6sdzuV9WFC7AEdY9enofIVn1fGt+YuuEhioUVTfaa9+E5kiFBjOUyVVOnM0bktmUU+TjNPP7lyj/uC9pupknvCdBr8R8AyK0aXhAa908Nx33bHoqfsyRqh73nM5BPH/OxJrZ811e648/wghLncnhxbP8vTqL+AWJ6E4MHrzpU+3j4dXAMd7n28WxUzKERJ4TA3dzZ5fVZ1VrII+EbcwJyAJ7zne4=
        APP_NAME: AGPMInjector
        DEVELOPER_NAME: 'Mac Developer: Henry Brock (4EJ5YAENFF)'
        PROFILE_NAME: TravisDevProfile.p12
      - secure: IzHCCyWsQB+47cqPXGrNk1jQU9hhl8JAPIevWixJOL+SQgPepfLRjUFZggURzA35eKzPzjNGc0/kqMXJ95OO6px7/DqY/ARPORjK4ObcOSUVOra6f+MFpT5AVvmTMFkcM6LD1bbxpFuK3S/Z+FCpIr84O/glGWoT3+cRT4ppmKomL0LRBoMJ3nx/LUM6dLH7F7CaMGOAlhLh7ZIv7DTPoGiVVGQE6euMhtpiZnJ0gsKHWf0xzg9Tt+4bP8R2eoI7SyJPsGBoVHSb5STUcbstYfiHf2fVnwsHyJYCjOMnw631jkyUXVEIMfFDw0Y+QPrM+Fpz9n3km2whG6+aoekpSl+ZSbTl3hX5yHfaZ2gf4Oo+3RdA9jMemXbSXa/pxVNSAcKQInq6vwtUqdGpmYezUu03SNgkpZxRanB5kZO3p2iq8axF8wIIipSp14T3YssAEPIWlF1H3waqxyMaFLRfsUS2iVTX3aXIbZGAFykbSKCNJRSmN1PKRQRrViKKwYEV1E/LI3jQ77FDCp8501j3u4qqdjK/989fcMLn9oKcoKvAJNPuBUx7ATii1ITn/8ckfTilsSysnW26IY9ML6Z9GF5n0TbbVYYilxO4tqISUg1d+HIEcaT+3qT9UArBdadvcO8oijkCgEXDjzq8zBNCGlVU+g/rbNwwl9EhSJX6atM=
script: xcodebuild -workspace AGPMInjector.xcworkspace -scheme AGPMInjector build
