language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project AGPMInjector.xcodeproj -scheme AGPMInjector
  -destination platform\=macOS | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X AGPMInjector.zip AGPMInjector.app
- cd ..
- cd ..
- mv build/Release/AGPMInjector.zip "$COMMIT.zip"
deploy:
  provider: releases
  api_key:
    secure: jRs9hwRsr6b9q4ExprUhPzfShDdElMdMjmLhztweX8O4/Pg1heU3kJGILxiwCLdby3Tw1Z/xvdRflZ6kY719TPim9z3Ymww6mAoYxoIR/g2fqxRn9Z8OF8sTwQ3pCAnH3BCdiW2OsyltGTM2JlrSs5LFGEAH5oDbhnnb4OI3ohrTfrAiao7IgkHWnqyqc3MG0mnxyCixS1p7JPluwI4GQAtrIljRLTet4p0BQONuZL5XYhgPlR7VeeiBnHH2WfrOKT3e9EyJolU4idN+VXGHxAIIflYuWLBCzva2mOglf+0Wm6dQdiQKKJqwlGKzHO0ifmU4WoL98JeA8PIk2GfJCB7Fs741tbZVmwZ78h4xl4Aw9CskFIAy7V4DGVUGgkEUYjV9P6aUfW8xMliAjJP9PR9yXx1IhIRs7SN4AyqFb6PgQYRPfivEnbhik+lqK+ZG90mogtecDyTgRI1KJNVUwWbJcykUNmwhpNKThS8VtFMK4U8nXTJgpKN4Eqes8ZqbZItpHQS4+8c1YrqbZ74x+rgOj4vXrjC4i4ZnVpl7BiC+zjnv8Snn5zHQhT9gU8rTfobJBVNO7ubmAE9duePGNMxcFcKS2450Exe54uLGLwI5Cds5jqepEMGIlcsCRUK37Ssz0jKxBNZXJIR02nU/UVF6W+X3PGAQQjOI2b1auwY=
  file: "$COMMIT.zip"
  on:
    repo: Pavo-IM/AGPMInjector
